#!/bin/bash

VERSION=0.0.4

declare list_file_name
declare list_dir_path="$HOME/.dmenu-game-launcher"

steam_menu() {
    declare -A id

    for manifest in $HOME/.steam/steam/steamapps/appmanifest_*; do
        name=$(cat $manifest | grep "name")
        if [[ ! $name =~ .*(Proton|Steamworks Common Redistributables).* ]]; then
            name="$(echo $name | cut -d' ' -f2- | sed -e 's/^"//' -e 's/"$//')"
            titles+=("$name")

            appid=$(cat $manifest | grep "\"appid\"")
            appid=$(echo $appid | cut -d' ' -f2-)
            id["$name"]=$(echo $appid | sed -e 's/^"//' -e 's/"$//')
        fi
    done

    IFS=$'\n' titles=($(sort <<< "${titles[*]}")); unset IFS

    game=$(printf '%s\n' "${titles[@]}" | dmenu -i "$@")

    [[ -n $game ]] || exit

    steam steam://rungameid/${id[$game]}
}

menu_template() {
    separatorStr='SEPARATOR'
    i=0
    declare -A commands
    while read line; do
        if [[ ${line:0:1} != '#' ]]; then
            titles[$i]="$(echo -e "${line%$separatorStr*}" | sed -e 's/[[:space:]]*$//')"
            commands["${titles[$i]}"]="${line#*$separatorStr}"
            ((i++))
        fi
    done < "$list_dir_path/$list_file_name.list"

    game=$(printf '%s\n' "${titles[@]}" | dmenu -i "$@")

    [[ -n $game ]] || exit

    if [[ $list_file_name == "dos" ]]; then
        sh -c "dosbox -exit ${commands[$game]}"
    elif [[ $list_file_name == "wine" ]]; then
        game_file_path="${commands[$game]}"
        sh -c "cd $(dirname $game_file_path) && wine $(basename $game_file_path)"
    else
        sh -c "${commands[$game]}"
    fi
}

gaming_apps() {
    # TODO
    app=$(printf '%s\n' "${app_name[@]}" | dmenu -i "$@")
}

menus+=("DOS games")
# menus+=("Gaming apps")
menus+=("Regular games")
menus+=("Steam games")
menus+=("Wine games")

option=$(printf '%s\n' "${menus[@]}" | dmenu -i "$@")

[[ -n $option ]] || exit

case $option in
    "DOS games")
        list_file_name="dos"
        menu_template
        ;;
    # "Gaming apps")
        #     gaming_apps
        #     ;;
    "Regular games")
        list_file_name="regular"
        menu_template
        ;;
    "Steam games")
        steam_menu
        ;;
    "Wine games")
        list_file_name="wine"
        menu_template
        ;;
    *)
        ;;
esac
